#Configuraciones generales del Framework

#Configuración de la base de datos
database:
  host: localhost
  name: smarty_lab
  user: root
  pwd: ive8mxii
  port: 3306
  codification: UTF-8
  db_timezone: es_MX

security:
  secret_key: alxsmora/95
  secret_iv: bk_208#leeshe
  method: AES-256-CBC

path:
  templates: App/Templates/
  controllers: App/Controllers/
  models: App/Models/

general:
  timezone: America/Mexico_City
  language: spanish
  path: localhost/TMF

twig:
  compiler: Core/compiler/
  reload: true
