#Configuraciones generales del Framework

#Configuración de la base de datos
database:
  host: localhost
  name: lab
  user: root
  pwd: 
  port: 3306
  codification: UTF-8
  db_timezone: es_MX

security:
  secret_key: 
  secret_iv: 
  method: AES-256-CBC

path:
  templates: App/Templates/
  controllers: App/Controllers/
  models: App/Models/

general:
  timezone: America/Mexico_City
  language: spanish
  path: http://localhost/Horizon/

twig:
  compiler: Core/compiler/
  reload: true
